### ISSUE TITLE
fixed?

### ISSUE THREAD

**Issue by ch-sander** [scta/scta-bundles#2]
https://github.com/scta/scta-bundles/blob/ef84f2f731dcb018c074d7918cdfa9549072c86f/FBG_Gotha_Chart_A_707_Descartes_duplicated_new_bundle.xml#L439

Should this lb be of the type fixed as well? I thought so, but in the edit we made together we haven't.

**Comment by jeffreycwitt** [comment]
Yes. I think it probably should. But I'm going to work on this weekend and explore whether it is needed or not.

**Comment by ch-sander** [comment]
Ok. I will do as you tell me on Monday morning
